# Descomposición de matrices

Consiste en encontrar dos o más matrices que puedan ayudar a escribir la matriz original y que tengan ciertas propiedades.

En el caso de una matriz cuadrada, esta se puede escribir como:

$A = autovectores.diagonal de los autovectores.matriz autovectores^{-1}$

In [1]:
import numpy as np

In [3]:
A = np.array([
    [3,2],
    [4,1]
])
print(A)

[[3 2]
 [4 1]]


In [5]:
eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues)
print(eigenvectors)

[ 5. -1.]
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


In [8]:
A_calc = eigenvectors.dot(np.diag(eigenvalues)).dot(np.linalg.inv(eigenvectors))
print(A_calc)

[[3. 2.]
 [4. 1.]]


Se puede observar como la matiz originalmente pudo ser descompuesta en los tres terminos, esto se verifica ya que al realizar producto interno entre ellos, se obtiene la matriz original.

## Matrices simétricas

Recordando que las matrices simétricas tienen como carácteristica que al realizar la transpuesta de ésta, se obtiene la misma matriz.

En el caso de la descomposición de matrices, se puede reemplazar el último termino de la inversa por la transpuesta. 

In [10]:
B = np.array([
    [3,2],
    [2,3]
])
print(B)

[[3 2]
 [2 3]]


In [12]:
print(B==B.T) # Verificación de matriz simétrica

[[ True  True]
 [ True  True]]


In [14]:
eigenvalues_B,eigenvectors_B = np.linalg.eig(B)
print(eigenvalues_B)
print(eigenvectors_B)

[5. 1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [16]:
B_calc= eigenvectors_B.dot(np.diag(eigenvalues_B)).dot(eigenvectors_B.T)
print(B_calc)

[[3. 2.]
 [2. 3.]]


Computacionalmente es más eficiente utilizar la transpuesta que la inversa

In [17]:
B_calc= eigenvectors_B.dot(np.diag(eigenvalues_B)).dot(np.linalg.inv(eigenvectors_B))
print(B_calc)

[[3. 2.]
 [2. 3.]]


Descomposición de matrices:
Consiste en reescribir una matriz cuadrada X como un producto de A x B x C, es decir X = AxBxC, donde:

- A: es la matriz formada por los autovectores
- B: matriz diagonal formada por los autovalores
- C: matriz inversa de A.

Nota: En matrices reales y simétricas, C = A.T (matriz traspuesta de los autovectores). Esta propiedad tiene menor costo computacional.