# Descomposición de matrices no cuadradas

En el caso de las matrices no cuadradas, no es posible utilizar autovalores y autovectores para descomponer la matriz.

Para descomponer matrices de este tipo, se puede utilizar el metodo de descomposición de valores singulares (SVD)

El cual llevaría la siguiente forma:

$A =S.V.D$, donde 

- A: matriz original
- S: vectores derechos singulares
- U: vectores izquierdos singulares
- D: es una matriz diagonal, con todos los valores singulares en su diagonal

Es importante recordar que S y U son ortogonales, por lo cual todos sus vectores son ortonormales.

In [1]:
import numpy as np

In [3]:
A = np.array([
    [1,2,3],
    [3,4,5]
])
print(A)

[[1 2 3]
 [3 4 5]]


In [12]:
U,D,V = np.linalg.svd(A)
print(U) # Sigulares izquierdos

[[-0.46410668 -0.88577931]
 [-0.88577931  0.46410668]]


In [13]:
print(np.diag(D)) # Matriz diagonal

[[7.97638869 0.        ]
 [0.         0.61418515]]


In [14]:
print(V) # Singulares derechos

[[-0.39133557 -0.5605708  -0.72980603]
 [ 0.8247362   0.13817999 -0.54837623]
 [ 0.40824829 -0.81649658  0.40824829]]


## Comprobación de la descomposición 

Como se puede observar, las matrices U y D tienen dimensiones (2,2), mientras que V es (3,3). Por lo cual se debe ajustar. Esto se puede realizar con el parámetro *full_matrices* de svd, también podrían añadirse una columna de 0 a la matriz diagonal para así poder realizarse la operación.

In [24]:
U,D,V = np.linalg.svd(A,full_matrices=False )
A_calc=U.dot(np.diag(D)).dot(V)
print(A_calc)

[[1. 2. 3.]
 [3. 4. 5.]]


In [31]:
np.allclose(A,A_calc) # Metodo para comparar si dos matrices son iguales

True

Otra forma 

In [25]:
U,D,V = np.linalg.svd(A)

In [27]:
D_complete = np.array([
    [D[0],0,0],
    [0,D[1],0]
])
print(D_complete)

[[7.97638869 0.         0.        ]
 [0.         0.61418515 0.        ]]


In [30]:
A_calc = U.dot(D_complete).dot(V)
print(A_calc)
np.allclose(A,A_calc)

[[1. 2. 3.]
 [3. 4. 5.]]


True