# Pseudo inversa de Moore Penrose


La pseudoinversa es una aplicación directa de svd (singular value decomposition), que permite resolver en multiples ocasiones sistemas de ecuaciones lineales.

La matriz pseudoinversa es utilizada cuando en un sistema de ecuaciones lineales, representado por:

 - $Ax = B$ 
 
 $x$ no tiene inversa. Esta operación es única y existe si se verifican 4 condiciones. Estas son:


- A⁺AA⁺ = A⁺ (idempotencia)
- AA⁺A = A (idempotencia)
- (AA⁺)ᵀ = AA⁺
- (A⁺A)ᵀ = A⁺A

Siendo A⁺ la pseudoinversa de la matriz A



In [1]:
import numpy as np
np.set_printoptions(suppress=True) # Con esto le decimos a numpy que todos los valores cercanos a cero, los ponga como ceros

El procedimiento para calcular r la pseudoinversa es el siguiente: 

1) Calcular las matrices $U$, $D$, y  $V$ (matrices SVD) de $A$.
2) Construir $D_(pse)$: una matriz de ceros que tiene igual dimension de $A$, y que luego se transpone.
3) Reemplazar la submatriz $D_pse[: D.shape[0], : D.shape[0]] por np.linalg.inv(np.diag(D))$
4) Reconstruir pseudoinversa: $A_(pse) = V.T.dot(D_pse).dot(U.T)$

In [4]:
A = np.array([
    [2,3],
    [5,7],
    [11,13]
])
print(A)
print(A.shape)

[[ 2  3]
 [ 5  7]
 [11 13]]
(3, 2)


1) Calcular las matrices $U$, $D$, y  $V$ (matrices SVD) de $A$.

In [6]:
U,D,V  = np.linalg.svd(A)
print('U')
print(U)
print('D')
print(D)
print('V')
print(V)

U
[[-0.18499741 -0.47276624 -0.86154979]
 [-0.44249308 -0.74271297  0.50257071]
 [-0.87748267  0.4742041  -0.07179582]]
D
[19.40321383  0.71783924]
V
[[-0.63055377 -0.77614557]
 [ 0.77614557 -0.63055377]]


2) Construir $D_(pse)$: una matriz de ceros que tiene igual dimension de $A$, y que luego se transpone.

In [29]:
D_pse = np.zeros((A.shape[0],A.shape[1])).T
print(D_pse)

[[0. 0. 0.]
 [0. 0. 0.]]


In [30]:
print(D_pse[:D.shape[0]])


[[0. 0. 0.]
 [0. 0. 0.]]


In [31]:
print('Valores a reemplazar en D_pse')
print(D_pse[:D.shape[0],:D.shape[0]])

Valores a reemplazar en D_pse
[[0. 0.]
 [0. 0.]]


In [32]:
print('Valores que pondremos en D_pse')
print(np.linalg.inv(np.diag(D)))

Valores que pondremos en D_pse
[[0.05153785 0.        ]
 [0.         1.39306957]]


3) Reemplazar la submatriz $D_pse[: D.shape[0], : D.shape[0]] por np.linalg.inv(np.diag(D))$

In [33]:
print('D_pse')
D_pse[:D.shape[0],:D.shape[0]] = np.linalg.inv(np.diag(D))
print(D_pse)

D_pse
[[0.05153785 0.         0.        ]
 [0.         1.39306957 0.        ]]


4) Reconstruir pseudoinversa: $A_(pse) = V.T.dot(D_pse).dot(U.T)$

In [35]:
A_pse = V.T.dot(D_pse).dot(U.T)
print(A_pse)

[[-0.50515464 -0.78865979  0.54123711]
 [ 0.42268041  0.67010309 -0.3814433 ]]


Se comprueba realizando producto interno entre la matriz A pseudoinversa con la matriz A, el resultado debe ser muy similar a la matriz identidad.

In [36]:
print(A_pse.dot(A))

[[ 1. -0.]
 [ 0.  1.]]


Si se desactiva la opción de aproximar los ceros, los resultados cambian. 

In [37]:
np.set_printoptions(suppress=False)

In [38]:
print(A_pse.dot(A))

[[ 1.00000000e+00 -1.77635684e-15]
 [ 4.44089210e-16  1.00000000e+00]]


La operación no es un conmutativa, por ello es diferente realizar producto interno $A_(pse).A$, el cual da como resultado la matruz identidad, que $A.A_(pse)$

In [39]:
print(A.dot(A_pse))

[[ 0.25773196  0.43298969 -0.06185567]
 [ 0.43298969  0.74742268  0.03608247]
 [-0.06185567  0.03608247  0.99484536]]


La pseudoinversa se puede obtener directamente como una herramienta de Numpy


In [42]:
print(np.linalg.pinv(A))
print(A_pse)

[[-0.50515464 -0.78865979  0.54123711]
 [ 0.42268041  0.67010309 -0.3814433 ]]
[[-0.50515464 -0.78865979  0.54123711]
 [ 0.42268041  0.67010309 -0.3814433 ]]


Otra forma de encontrar la pseudoinversa es la siguiente:

In [47]:
A_pse2 = np.linalg.inv(A.T.dot(A)).dot(A.T)
print(A_pse2)

[[-0.50515464 -0.78865979  0.54123711]
 [ 0.42268041  0.67010309 -0.3814433 ]]
